version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - micro_services:/data/db
    attach: false
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn start:dev reservations
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

volumes:
  micro_services: